IT-3773: Add managed policies
Sage-Bionetworks-IT/organizations-infra pull request #1211
Opened 2024-09-12 16:51 UTC by xschildw

This PR splits the inline policy from #1208 into 3 managed policies along the types of resources (bucket, file, distributions).

2024-09-12 22:55 UTC, xschildw commented on org-formation/650-identity-providers/_tasks.yaml
> +SynapseMonorepoBucketAccessPolicy:
Done.

2024-09-13 17:54 UTC, zaro0508 requested changes

2024-09-13 17:54 UTC, zaro0508 commented on org-formation/650-identity-providers/_tasks.yaml
> +    PolicyDocument: !Sub >-
there's no references in these policy douments.  i don't think you need `!Sub`?

2024-09-13 19:44 UTC, zaro0508 requested changes

2024-09-13 19:44 UTC, zaro0508 commented on org-formation/650-identity-providers/_tasks.yaml
> +    PolicyDocument: |
since it's json spacing don't matter therefore using `>-` should give you the most compact solution. https://yaml-multiline.info/

2024-09-13 20:26 UTC, zaro0508 approved these changes

2024-09-16 15:44 UTC, merged