IT-3924: Add prod account
Sage-Bionetworks-IT/organizations-infra pull request #1231
Opened 2024-09-30 18:10 UTC by xschildw

This PR creates the AWS account to host the Synapse LLM infrastructure.

Note: dev account to be deleted per discussion.

2024-09-30 19:50 UTC, zaro0508 requested changes

2024-09-30 19:50 UTC, zaro0508 commented on org-formation/organization.yaml
> +  SynapseLlmProdAccount:
how about add to one of the OUs above?

2024-09-30 19:58 UTC, xschildw commented on org-formation/organization.yaml
> +  SynapseLlmProdAccount:
Oops...

2024-10-01 15:34 UTC, zaro0508 approved these changes

2024-10-01 16:12 UTC, merged