Add shared Nextflow accounts under ScienceOU
Sage-Bionetworks-IT/organizations-infra pull request #130
Opened 2021-04-06 21:28 UTC by BrunoGrandePhD

I'm opening this PR to create development and production AWS accounts for running Nextflow workflows. The intent is that the production account will be used on PHI data, so it needs to be HIPAA compliant. The development account will used to determine the minimal policies, etc. required for the production account. This assumes that we will have more access to the development account than the production account. 

Currently, this PR is marked as a draft because I'm waiting to hear back from Khai on whether I should use the `ScienceOU` in the meantime or wait until we split into `ScienceDevOU` and `ScienceProdOU`. I'm also unsure about which department this should be tagged with since this will span SysBio and CompOnc. 

----

PR Checklist:
[x] Describe and explain your intentions for this change

[x] Setup pre-commit and run the validators (info in README.md)
    To validate files run: `pre-commit run --all-files`

2021-04-06 22:29 UTC, zaro0508 requested changes

2021-04-06 22:29 UTC, zaro0508 commented on org-formation/organization.yaml
> +      RootEmail: aws-nextflow-workflows@sagebase.org
AWS requires a unique email address for every account.

2021-04-06 22:29 UTC, zaro0508 commented on org-formation/organization.yaml
> +      Alias: org-sagebase-nextflow-workflows-shared-dev
do we really need `shared`?  seems kinda implicit to me.

2021-04-06 22:30 UTC, zaro0508 commented
would you mind splitting this to two PRs? one for each account?

2021-04-06 22:56 UTC, BrunoGrandePhD commented
@zaro0508: I've restricted this PR to the production account. See #131 for the development account. I've made sure different root emails are used, and I've removed the implied `shared` from the names. Thanks!

2021-04-07 21:11 UTC, zaro0508 approved these changes

2021-04-08 02:16 UTC, ahayden approved these changes
There will be some manual steps to take care of after this.

2021-04-08 18:48 UTC, BrunoGrandePhD commented on org-formation/organization.yaml
> +        - !Ref NextflowWorkflowsProdAccount
I prefer your naming convention. And I expect this account to be reserved for Nextflow-related resources. 

@tthyer: Let us know if you have something else in mind.

2021-04-08 18:49 UTC, BrunoGrandePhD commented
I'm going with the CompOnc imCORE project for now since this work will be used to deploy workflows for processing imCORE data. This might change in a separate PR if I'm instructed of a better department/project for an AWS account shared between SysBio and CompOnc.

2021-04-09 05:34 UTC, merged