[IT-1186] Set up JumpCloud access for Nextflow Prod account
Sage-Bionetworks-IT/organizations-infra pull request #135
Opened 2021-04-08 23:24 UTC by BrunoGrandePhD

This PR builds on top of #130 and sets up access to the AWS account via JumpCloud. I don't expect to be granted admin access on this account. I'm thinking that Sage IT can log into the account to create the service user and role required for me to set up the provisioner repository. 

- [ ] If I understand correctly, @zaro0508 or @ahayden needs to generate the metadata document and store it as `workflows-nextflow-prod-admin.xml`. 

----

### PR Checklist
- [x] Describe and explain your intentions for this change
- [x] Setup pre-commit and run the validators (info in README.md)
  To validate files run: `pre-commit run --all-files`

2021-04-09 05:25 UTC, zaro0508 requested changes

2021-04-09 05:25 UTC, zaro0508 commented on org-formation/organization.yaml
> +  WorkflowsNextflowProdAccount:
this is already in PR #135

2021-04-09 21:46 UTC, BrunoGrandePhD commented
I've added the metadata document that @zaro0508 provided on Slack. I also merged the `master` branch into this PR.

2021-04-12 23:25 UTC, BrunoGrandePhD commented
@ahayden: Do you want to track the manual steps for setting up this production account here or on [IT-1186](https://sagebionetworks.jira.com/browse/IT-1186)?

2021-04-13 15:48 UTC, zaro0508 approved these changes

2021-04-13 16:06 UTC, BrunoGrandePhD commented
@zaro0508: I dealt with the merge conflict.

2021-04-13 18:18 UTC, merged