[IT-1186] Set up JumpCloud access for Nextflow Dev account
Sage-Bionetworks-IT/organizations-infra pull request #136
Opened 2021-04-08 23:26 UTC by BrunoGrandePhD

This PR builds on top of #131 and sets up access to the AWS account via JumpCloud. Since this is a development/sandbox account, it would be nice to be granted access to this role. This would allow me to create the role required for me to set up the provisioner repository, which needs to be configured to trust the service user mentioned in #135. 

- [ ] If I understand correctly, @zaro0508 or @ahayden needs to generate the metadata document and store it as `workflows-nextflow-dev-admin.xml`. 

----

### PR Checklist
- [x] Describe and explain your intentions for this change
- [x] Setup pre-commit and run the validators (info in README.md)
  To validate files run: `pre-commit run --all-files`

2021-04-09 05:23 UTC, zaro0508 requested changes

2021-04-09 05:23 UTC, zaro0508 commented on org-formation/organization.yaml
> +  WorkflowsNextflowDevAccount:
this portion was already done in PR #131 ?

i think you may need to bring this current with master.

2021-04-09 21:46 UTC, BrunoGrandePhD commented
I've added the metadata document that @zaro0508 provided on Slack. I also merged the `master` branch into this PR.

2021-04-10 00:32 UTC, zaro0508 approved these changes

2021-04-10 00:32 UTC, merged