[IT-1178] Setup SSO access to AWS scipool accounts
Sage-Bionetworks-IT/organizations-infra pull request #180
Opened 2021-05-13 00:16 UTC by zaro0508

Setup to allow users in the JC scipool admin and scipool community manager
groups access to AWS scipooldev and scipoolprod accounts.  We setup the
admin and a community manager roles.

2021-05-13 17:23 UTC, brucehoff requested changes

2021-05-13 17:23 UTC, brucehoff commented on org-formation/700-aws-sso/_tasks.yaml
> +  StackName: !Sub '${resourcePrefix}-${appName}-scipoolprod-community-manager'
shouldn't this be:
```
StackName: !Sub '${resourcePrefix}-${appName}-scipoolprod-admin'
```
?

2021-05-13 23:09 UTC, zaro0508 commented on org-formation/700-aws-sso/_tasks.yaml
> +  StackName: !Sub '${resourcePrefix}-${appName}-scipoolprod-community-manager'
yes, fixed.  thanks.

2021-05-13 23:23 UTC, brucehoff approved these changes

2021-05-14 01:47 UTC, ahayden requested changes
Shouldn't stridespool be part of this change?

2021-05-14 03:57 UTC, zaro0508 commented
no @ahayden , strides account is not under our organization account therefore we cannot manage it with org-formation.  We have the SAML integration for strides and we'll probably need to keep it like that.

2021-05-17 17:29 UTC, ahayden commented
We will still have strides through Jumpcloud SAML directly (not AWS SSO).

2021-05-17 17:30 UTC, ahayden approved these changes
Looks good

2021-05-17 19:21 UTC, merged