[IT-1389] Create service accounts
Sage-Bionetworks-IT/organizations-infra pull request #276
Opened 2021-08-26 19:50 UTC by thomasyu888

PR Checklist:
- [x] Describe and explain your intentions for this change
- [x] Setup pre-commit and run the validators (info in README.md)

2021-08-30 16:02 UTC, zaro0508 requested changes
looks good, just a few minor fix ups and should be good to go.

2021-09-01 18:13 UTC, thomasyu888 commented on org-formation/600-access/_tasks.yaml
> +CnbCIServiceAccounts:
```suggestion
CnbCIServiceAccount:
```

2021-09-01 18:14 UTC, thomasyu888 commented on org-formation/600-access/_tasks.yaml
> +    Region: us-east-1
```suggestion
    Region: !Ref primaryRegion
```

2021-09-01 19:51 UTC, zaro0508 approved these changes

2021-09-01 20:58 UTC, merged