[IT-1749] Setup redirect to SSO URL
Sage-Bionetworks-IT/organizations-infra pull request #632
Opened 2022-11-08 04:44 UTC by zaro0508

The SSO URL is difficult to remember so we are setting up an easier to remember URL to redirect to the SSO endpoint.

2022-11-08 19:05 UTC, brucehoff requested changes
Just a couple typo's.

2022-11-08 19:05 UTC, brucehoff commented on org-formation/800-redirects/README.md
> +The templates in this folder sets up convienient redirects to other difficult to
Typos: 'sets up'->'set up'; 'convienient'->'convenient'

2022-11-09 16:46 UTC, zaro0508 commented on org-formation/800-redirects/README.md
> +The templates in this folder sets up convienient redirects to other difficult to
fixed

2022-11-09 17:00 UTC, xschildw approved these changes

2022-11-14 18:50 UTC, brucehoff approved these changes

2022-11-14 20:16 UTC, merged