[ETL-275] Add recover development account under ScienceDevOU
Sage-Bionetworks-IT/organizations-infra pull request #649
Opened 2022-12-07 19:32 UTC by rxu17

Hello,
I'm opening this PR to create a development AWS account. This development account paired with the production account will house all the ETL work required for the RECOVER project, such that all the work done in these accounts will be charged to the RECOVER grant. 

See [insert link here once created] for the PR creating the corresponding production account.

PR Checklist:
[X] Describe and explain your intentions for this change
[X] Setup pre-commit and run the validators (info in README.md)

2022-12-07 20:02 UTC, thomasyu888 commented
So I think Brad had suggested we also include the dev account under production accounts. Or maybe there needs to be a new category of FISMA Accounts

2022-12-08 23:19 UTC, brucehoff requested changes

2022-12-09 00:18 UTC, thomasyu888 commented on org-formation/organization.yaml
> +      RootEmail: aws-recover-dev@sagebase.org
Done

2022-12-09 00:39 UTC, rxu17 commented on org-formation/organization.yaml
> +      AccountId: '634761300905'
Done

2022-12-09 22:16 UTC, brucehoff commented on org-formation/organization.yaml
> +      RootEmail: aws-recover-dev@sagebase.org
Please note that "who can post" needs to be set to "anyone on the web" lest AWS is unable to send emails to the alias: https://groups.google.com/a/sagebase.org/g/aws-recover-dev/settings?hl=en

2022-12-09 22:16 UTC, brucehoff commented
LGTM but I'd like @zaro0508 to approve since this is my first time reviewing an account creation PR.

2022-12-09 22:35 UTC, thomasyu888 commented on org-formation/organization.yaml
> +      RootEmail: aws-recover-dev@sagebase.org
Done! Thanks!

2022-12-12 23:50 UTC, brucehoff approved these changes

2022-12-12 23:52 UTC, brucehoff commented
@rxu17 The PR says, "This branch has conflicts that must be resolved".  Would you please have a look?

2022-12-13 00:26 UTC, rxu17 commented
Conflicts resolved

2022-12-13 01:35 UTC, merged