Ibcdpe 441 create dpe aws
Sage-Bionetworks-IT/organizations-infra pull request #676
Opened 2023-01-10 23:30 UTC by thomasyu888

PR Checklist:
- [x] Describe and explain your intentions for this change
- [x] Setup pre-commit and run the validators (info in README.md)

2023-01-10 23:31 UTC, thomasyu888 commented on org-formation/organization.yaml
> +        AccountOwner: thomas.yu@sagebase.org
```suggestion
        AccountOwner: thomas.yu@sagebase.org
        CostCenter: NO PROGRAM / 000000
```

2023-01-12 01:21 UTC, brucehoff requested changes

2023-01-12 01:21 UTC, brucehoff commented on org-formation/organization.yaml
> +      Alias: org-sagebase-dpe-dpe
Did you mean `org-sagebase-dpe-dev`?

2023-01-12 15:50 UTC, thomasyu888 commented on org-formation/organization.yaml
> +      Alias: org-sagebase-dpe-dpe
```suggestion
      Alias: org-sagebase-dpe-dev
```

2023-01-12 17:37 UTC, brucehoff approved these changes

2023-01-13 17:14 UTC, thomasyu888 commented
Thanks @brucehoff !

2023-01-13 21:38 UTC, thomasyu888 commented
@brucehoff One thing I changed, was that I made this a production account, since we may be interacting with systems that house sensitive data within this account.  

We will continue using the DnT-dev account for sole development purposes.

2023-01-18 22:50 UTC, brucehoff approved these changes

2023-01-19 19:27 UTC, merged