[IT-2549] Add certificate for finops-api.sageit.org
Sage-Bionetworks-IT/organizations-infra pull request #726
Opened 2023-02-09 00:21 UTC by jesusaurus

Once this certificate has been manually validated, it can be added to the mips microservice cloudfront distribution.

2023-02-09 16:09 UTC, zaro0508 reviewed
I like this idea however certificate creation requires a manual DNS validation step therefore this is not fully automated and worse it will hang waiting for validation.

Also I think it may make more sense adding this to cfn template for the app because it's just another resource that the app needs.

2023-02-09 16:49 UTC, xschildw reviewed
I like the idea too, we'll have to deal with the validation no matter what. It would also make it easier to reuse certs if possible (i.e. can't we create a cert covering *.sageit.org that would cover all the endpoints).

2023-02-13 21:48 UTC, jesusaurus commented
Deploy a new wildcard certificate for sageit.org in both the SageIT and
the AdminCentral accounts. This is intended to replace the certificate
created in by sceptre in the SageIT account, and to be used by the
finops lambdas.

2023-02-14 17:04 UTC, xschildw approved these changes

2023-02-14 17:37 UTC, zaro0508 requested changes

2023-02-14 17:37 UTC, zaro0508 commented on org-formation/010-certificates/_tasks.yaml
> +      - !Ref SageITAccount
i need to think about this

2023-03-02 22:08 UTC, zaro0508 approved these changes

2023-03-03 16:21 UTC, merged