[DCA-8] AWS account for Schematic app
Sage-Bionetworks-IT/organizations-infra pull request #734
Opened 2023-02-21 22:47 UTC by zaro0508

Create an AWS account to run Schematica appp[1]

[1] https://github.com/Sage-Bionetworks/schematic

2023-02-21 22:53 UTC, xschildw approved these changes
As long as TBD is valid value for costCenter...

2023-02-21 23:00 UTC, zaro0508 commented on org-formation/organization.yaml
> +        CostCenter: "TBD"
@brucehoff @milen-sage please check Department/Project/AccountOwner and CostCenter are correct.

2023-02-22 01:54 UTC, brucehoff requested changes
I though we agreed just to use the 'dca-prod' account for both the DCA app' and the Schematic APIs.  The account was already set up, under DCA-8.  What is the benefit of a separate AWS account fir one part of the system?

2023-02-22 04:17 UTC, zaro0508 commented
@brucehoff we had discussions but i don't remember us making a decision one way or the other.  The benefits of separate account for schematic is to provide full security isolation of the two apps.  This could be important if we think that (one day) the apps would have a separate set of developers managing and maintaining them.  If that's not important then deploying both to the same AWS account is fine.

2023-02-22 15:25 UTC, brucehoff commented
> @brucehoff we had discussions but i don't remember us making a decision one way or the other. The benefits of separate account for schematic is to provide full security isolation of the two apps. This could be important if we think that (one day) the apps would have a separate set of developers managing and maintaining them. If that's not important then deploying both to the same AWS account is fine.

i think the two app's will always be maintained by the same team and so it's OK to deploy them together.  We can check with @milen-sage.

2023-02-23 00:10 UTC, zaro0508 commented
OK.  no need to create new aws account so closing this PR.

2023-02-23 00:10 UTC, closed without merging