create AWS account for queen Tess
Sage-Bionetworks-IT/organizations-infra pull request #81
Opened 2021-02-25 19:02 UTC by zaro0508

2021-02-26 17:45 UTC, ahayden requested changes
negative

2021-03-24 17:53 UTC, ahayden requested changes
This would be a dev account owned by Tess, but should be named after the project its for.

2021-03-24 17:53 UTC, ahayden commented on org-formation/organization.yaml
> +        - !Ref TThyerAccount
Let's rename this `MobileHealth-DataEngineeringAccount`

2021-03-24 17:53 UTC, ahayden commented on org-formation/organization.yaml
> +      AccountName: org-sagebase-tthyer
This should be `org-sagebase-mobilehealth-dataengineering`

2021-03-24 17:53 UTC, ahayden commented on org-formation/organization.yaml
> +      Alias: org-sagebase-tthyer
This should be `org-sagebase-mobilehealth-dataengineering`

2021-03-24 18:34 UTC, ahayden approved these changes
Thank you!

2021-03-24 18:34 UTC, ahayden commented on org-formation/organization.yaml
> +      RootEmail: aws-mobilehealth-dataengineering@sagebase.org
Nice- I forgot about this

2021-03-24 20:11 UTC, tthyer approved these changes

2021-03-24 20:38 UTC, merged