add empty line to trigger PR
Sage-Bionetworks-IT/organizations-infra pull request #851
Opened 2023-05-03 15:15 UTC by linglp

PR Checklist:
[x] Describe and explain your intentions for this change
[x] Setup pre-commit and run the validators (info in README.md)

Depends on https://github.com/Sage-Bionetworks/schematic-infra/pull/29

2023-05-03 16:42 UTC, zaro0508 approved these changes

2023-05-04 17:30 UTC, zaro0508 requested changes

2023-05-04 17:52 UTC, linglp commented on org-formation/800-redirects/_tasks.yaml
> +    TargetHostName: !CopyValue ['schematic-staging-DockerFargateStack-LoadBalancerDNS', !Ref DCAProdAccount]
Thanks. Just updated that.

2023-05-04 17:57 UTC, zaro0508 approved these changes

2023-05-04 17:58 UTC, merged