[IT-2768] Update role name for CI
Sage-Bionetworks-IT/organizations-infra pull request #861
Opened 2023-05-09 21:01 UTC by zaro0508

The CI role names to assume will change due to PR #859.
update to the new role names

depends on PR #859

2023-05-09 21:42 UTC, xschildw approved these changes

2023-05-11 21:44 UTC, jesusaurus requested changes

2023-05-11 21:44 UTC, jesusaurus commented on .github/workflows/main.yaml
> +      role-to-assume: "arn:aws:iam::237179673806:role/sagebase-github-oidc-sage-ProviderRo"
this looks like a typo

2023-05-11 22:14 UTC, jesusaurus approved these changes

2023-05-12 00:57 UTC, merged