GH OIDC for deployment to strides-ampad-workflows account
Sage-Bionetworks-IT/organizations-infra pull request #907
Opened 2023-06-23 21:10 UTC by zaro0508

Commit bdfc556 had setup github OIDC access for the Sage-Bionetworks-Workflows/nextflow-infra repo.  However that setup didn't work because the template used was not adequate and needed to be reverted in commit f6de736

Now we need to redo the setup for strides with the help of PR https://github.com/Sage-Bionetworks/aws-infra/pull/394

depends on https://github.com/Sage-Bionetworks/aws-infra/pull/394

2023-06-23 21:26 UTC, xschildw commented on sceptre/strides-ampad-workflows/config/prod/github-oidc-provider.yaml
> +  url: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.7.5/templates/IAM/oidc-provider.j2
This one .yaml

2023-06-23 21:35 UTC, xschildw requested changes
Don't we need a dependency on oidc_provider.yaml to make sure we don't use it b4 it's setup (or does the !stack_output do it)?

2023-06-23 21:53 UTC, zaro0508 commented
> Don't we need a dependency on oidc_provider.yaml to make sure we don't use it b4 it's setup (or does the !stack_output do it)?

`!stack_output` does setup a dependency between the two files automatically while `!stack_ouput_external` does not

2023-06-23 22:07 UTC, xschildw requested changes
the ref to https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.7.5/templates/IAM/oidc-provider.j2 should be https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.7.5/templates/IAM/oidc-provider.yaml (line 3 in sceptre/strides-ampad-workflows/config/prod/github-oidc-provider.yaml).

2023-06-23 22:33 UTC, xschildw approved these changes

2023-06-26 17:06 UTC, merged

2023-06-26 17:13 UTC, xschildw approved these changes
Why does not stack_output work?